### PR TITLE
Review - PyCall and Conda Configuration

### LINKED ISSUE #40: Unable to install - missing python packages
```
[ Info: Installing trackpy via the Conda trackpy package...
[ Info: Running `conda install -y trackpy` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - trackpy

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


ERROR: InitError: failed process: Process(setenv(`'C:\Users\nicho\.julia\conda\3\Scripts\conda.exe' install -y trackpy`,["WINDIR=C:\\WINDOWS", "PATH=C:\\Users\\nicho\\.julia\\conda\\3\\Library\\bin;C:\\Users\\nicho\\.julia\\conda\\3\\Library\\bin;C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.3.7.0_x64__8wekyb3d8bbwe;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Program Files\\PowerShell\\7\\;C:\\Users\\nicho\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\nicho\\AppData\\Local\\gitkraken\\bin;C:\\Users\\nicho\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\ProgramData\\nicho\\GitHubDesktop\\bin;C:\\Users\\nicho\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\Users\\nicho\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\nicho\\.dotnet\\tools;", "USERDOMAIN_ROAMINGPROFILE=AURORASURFACE8", "WSLENV=WT_SESSION:WT_PROFILE_ID:", "LOCALAPPDATA=C:\\Users\\nicho\\AppData\\Local", "HOMEPATH=\\Users\\nicho", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 140 Stepping 1, GenuineIntel", "NUMBER_OF_PROCESSORS=8", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL", "SESSIONNAME=Console"  …  "PROCESSOR_LEVEL=6", "SW_SIM_HYDRA=C:\\Program Files\\Common Files\\SolidWorks Shared\\Simulation Worker Agent\\", "SYSTEMDRIVE=C:", "=C:=C:\\Users\\nicho", "PROGRAMW6432=C:\\Program Files", "TEMP=C:\\Users\\nicho\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "OPENBLAS_MAIN_FREE=1", "PROCESSOR_ARCHITECTURE=AMD64", "PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ .\process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base .\process.jl:480
  [3] run
    @ .\process.jl:477 [inlined]
  [4] runconda(args::Cmd, env::String)
    @ Conda C:\Users\nicho\.julia\packages\Conda\2lg2O\src\Conda.jl:128
  [5] add(pkg::String, env::String; channel::String, satisfied_skip_solve::Bool, args::Cmd)
    @ Conda C:\Users\nicho\.julia\packages\Conda\2lg2O\src\Conda.jl:256
  [6] add (repeats 2 times)
    @ C:\Users\nicho\.julia\packages\Conda\2lg2O\src\Conda.jl:239 [inlined]
  [7] pyimport_conda
    @ C:\Users\nicho\.julia\packages\PyCall\ilqDX\src\PyCall.jl:721
  [8] pyimport_conda
    @ C:\Users\nicho\.julia\packages\PyCall\ilqDX\src\PyCall.jl:715 [inlined]
  [9] __init__()
    @ MicroTracker C:\Users\nicho\.julia\packages\MicroTracker\2n7hT\src\MicroTracker.jl:16
 [10] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1115
 [11] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base .\loading.jl:1061
 [12] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base .\loading.jl:1506
 [13] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1783
 [14] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1660
 [15] macro expansion
    @ .\loading.jl:1648 [inlined]
 [16] macro expansion
    @ .\lock.jl:267 [inlined]
 [17] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1611
during initialization of module MicroTracker

caused by: PyError (PyImport_ImportModule

The Python package trackpy could not be imported by pyimport. Usually this means
that you did not install trackpy in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the trackpy module, you can
use `pyimport_conda("trackpy", PKG)`, where PKG is the Anaconda
package that contains the module trackpy, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'trackpy'")

Stacktrace:
  [1] pyimport(name::String)
    @ PyCall C:\Users\nicho\.julia\packages\PyCall\ilqDX\src\PyCall.jl:558
  [2] pyimport_conda
    @ C:\Users\nicho\.julia\packages\PyCall\ilqDX\src\PyCall.jl:716
  [3] pyimport_conda
    @ C:\Users\nicho\.julia\packages\PyCall\ilqDX\src\PyCall.jl:715 [inlined]
  [4] __init__()
    @ MicroTracker C:\Users\nicho\.julia\packages\MicroTracker\2n7hT\src\MicroTracker.jl:16
  [5] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1115
  [6] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base .\loading.jl:1061
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base .\loading.jl:1506
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1783
  [9] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1660
 [10] macro expansion
    @ .\loading.jl:1648 [inlined]
 [11] macro expansion
    @ .\lock.jl:267 [inlined]
 [12] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1611
```

```
Julia Version 1.9.3
Commit bed2cd540a (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
  JULIA_PKG_USE_CLI_GIT = true
```

### PR DESCRIPTION
**Pull request by czimm79**
This PR contains responses to reviewer comments regarding MicroTracker's interface with Python using PyCall and Conda.

## Missing trackpy package
https://github.com/czimm79/MicroTracker.jl/issues/40#issue-1934327133
It appears that the `conda-forge` channel was not added in when installing the Conda environment on your machine. This should be fixed by [fc0f771](https://github.com/czimm79/MicroTracker.jl/pull/47/commits/fc0f7718a6e299185cc0e8f63f63f006f6b472ad) by explicitly stating that trackpy is contained in the Conda-forge channel. To further verify, I've added Windows GitHub actions CI testing on this PR.

Closes #40.

_Originally posted by @mkitti in https://github.com/openjournals/joss-reviews/issues/5804#issuecomment-1748087989_

> This Julia package has Python package dependencies. There is no mention of this in the Quick Start or Setup portions of the documentation. However, the interface between Python and Julia often needs careful configuration. In particular, the authors use the function `pyimport_conda` from PyCall.jl. Proper use of this function requires that both the packages Conda.jl and PyCall.jl be consistently configured. The authors should at minimum note the use of these dependencies and reference the documentation for those packages.
> 
> The versions of the Julia and Python dependencies should be listed for reproducibility.
> 
> Automated testing does exist in the form of Julia tests and is run by Github Actions on each commit. This obviously only works with a properly installed package including with the Python dependencies.

_Originally posted by @mkitti in https://github.com/openjournals/joss-reviews/issues/5804#issuecomment-1748059398_

It appears that PyCall currently [does not support](https://github.com/JuliaPy/Conda.jl/blob/master/README.md#conda-environments) non-root Conda environments. So, I've added documentation describing the use of Conda and PyCall in MicroTracker and noted that the packages install into the ROOT environment. This documentation has been added in the "Setting Up" section, and a link was added in the quick-start guide pointing users to that section.

When loading PyCall, I've forced that the Python interpreter that Julia uses is set to the root Conda.jl environment ([b32af47](https://github.com/czimm79/MicroTracker.jl/pull/47/commits/b32af47a3b02fa6cb836e71da7b31051949af925)) using the PYTHON environment variable. In commit [74176fd](https://github.com/czimm79/MicroTracker.jl/pull/47/commits/74176fd9e9462903d8a5ac4fdadb852f4f573c03) I remove the use of `pyimport_conda` and explicitly add packages using `Conda.add`. Then, to prevent a verbose message every time MicroTracker is imported, a check is performed to see if the necessary packages are present in the Conda environment.

### CODE REVIEW

**Comment by mkitti** [comment]
> It appears that PyCall currently [does not support](https://github.com/JuliaPy/Conda.jl/blob/master/README.md#conda-environments) non-root Conda environments.

The main thing PyCall.jl needs to know is which `python` executable to use. In the PyCall.jl README, it specifies that you can manually set this by doing `ENV["PYTHON"] = /path/to/python`. This includes a `python` contained with a conda environment.

https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version

```
$ mamba create -n trackpy_test -c conda-forge trackpy
$ mamba activate trackpy_test
$ which python
/Users/mkitti/miniforge3-arm64/envs/trackpy_test/bin/python
$ cd $CONDA_PREFIX
$ PYTHON=`which python` julia --project=. -e 'using Pkg; Pkg.add(["PyCall", "Conda"]); Pkg.build("PyCall")' 
$ julia --project=. -E 'using PyCall; pyimport("trackpy")'
PyObject <module 'trackpy' from '/Users/mkitti/miniforge3-arm64/envs/trackpy_test/lib/python3.12/site-packages/trackpy/__init__.py'>
$ julia --project=. -e 'using Conda; Conda.add("pandas", pwd())'
```

`Conda.ROOTENV` is just the default environment if not specified in calls such as `Conda.add`. Thus, I'm a bit confused by the author's statement.

**Review by mkitti — CHANGES_REQUESTED** [review]
There are misstatements here and some logical flaws.

PyCall.jl itself does not necessarily know about conda environments. What it does use is the location of a Python executable. If you point PyCall.jl to a Python executable within a conda environment, then it will use that environment.

Note that configuring PyCall.jl is a two step process.
1. Set `ENV["PYTHON"]`
2. Call `Pkg.build("PyCall")`

The code as written attempts to do step 1 but does not do step 2 or request that the user does step 2.

Also, before trying to set `ENV["PYTHON]` , check if the user has already done so. Do not override the user if they have this set.

**Comment by czimm79** [comment]
I see - thanks for clearing this up. It does appear I misinterpreted the documentation! I'll incorporate your suggestions and get a new commit finished by the end of the week. I'll tag you when finished.

**Comment by czimm79** [comment]
When attempting to run `Pkg.build("PyCall")` in the `init()` block of the module, I now get a segmentation fault error. I believe this has something to do with marking the module as safe to precompile yet rebuilding inside it. I'm looking into this further.

**Comment by mkitti** [comment]
Perhaps calling `Pkg.build` should be left to the user. I would just check to see if it is consistent with `PyCall.pyprogramname` and advise the user to rebuild if that is not the case.

**Comment by czimm79** [comment]
That's a great idea, thanks! Will do that.

**Comment by czimm79** [comment]
Hi @mkitti - I've made the requested change and updated the docs to instruct the user how to set which Python environment to use. Anything else before I merge this PR? Thanks.

**Comment by mkitti** [comment]
I think these changes should be sufficient to address my concerns. Thank you for making them.

I do not have the ability to directly test at the moment, but we can proceed. If I see any further issues, I will report them independently of the review.

**Comment by czimm79** [comment]
Sounds good, thank you!

**Pull request merged**
